clippy:
    cargo clippy --fix --allow-dirty --allow-staged --lib --bins --tests --all-features

run problem:
    cargo run --bin euler --release -- {{ problem }}

bench benchmark="":
    @{{ if benchmark != "" { "cargo +nightly bench --bench " + benchmark } else { "cargo +nightly bench" } }}
